### ISSUE TITLE
Error while running the action 

### ISSUE THREAD

**Issue by sanjogpandasp** [AppThreat/cdxgen-action#3]
I get the below error while running the action using the below settings. 

```
- uses: AppThreat/cdxgen-action@v1
  with:
    output: "./reports/bom.xml"
    serverUrl: "https://[internal host for dtrack]"
    apiKey: ${{ secrets.apiKey }}
```

**Error message**
`Error: form-data: Arrays are not supported.`

**Comment by prabhu** [comment]
@sanjogpandasp thank you for reporting this issue. Could you kindly investigate further and let me know where the issue is? I could guide you to creating a pull request.

**Comment by sanjogpandasp** [comment]
I am using the below workflow file, but I do not see any output on the console. 

```
name: CI

on: [push]
jobs:
  build:
    runs-on: linux
    steps:
      - uses: AppThreat/cdxgen-action@v1
```

The output is pasted below
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/5404943/145044082-a9be72bb-82c9-4418-8167-f76c71ca8386.png">
